openapi: 3.0.0
info:
  title: Ratna API Title
  description: Ratna Course Title
  version: "1.0"
  contact:
    name: enrollment entity
    url: https://www.google.com/
    email: mailto:ratnasree@hotmail.com
  termsOfService: https://www.google.com/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: http://localhost:9090
    variables:
      server:
        default: localhost
        description: This value is assigned by server producer
      port:
        enum:
          - "9090"
          - "443"
        default: "9090"
      version:
        default: v1
    description: localhost courses
paths:
  /v1/course:
    get:
      summary: list all courses
      description: return all courses
      responses:
        '200':
          description: list of all courses
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    name:
                      type: string
                    lastUpdatedDate:
                      type: string
                    createdDate:
                      type: string
                    isDeleted:
                      type: boolean

    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
                name:
                  type: string
                lastUpdatedDate:
                  type: string
                createdDate:
                  type: string
                isDeleted:
                  type: boolean
      responses:
        '200':
          description: OK
    put:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
                name:
                  type: string
                lastUpdatedDate:
                  type: string
                createdDate:
                  type: string
                isDeleted:
                  type: boolean
      responses:
        '200':
          description: OK
  /v1/course/{id}:
    get:
      parameters:
        - name: id
          in: path
          schema:
            type: number
            minimum: 1
            maximum: 100000
          example: 10002
      responses:
        '200':
          description: course details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  lastUpdatedDate:
                    type: string
                  createdDate:
                    type: string
                  isDeleted:
                    type: boolean
    delete:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
            minimum: 1
            maximum: 100000
          example: 10002
      responses:
        '200':
          description: OK
  /v1/persons:
    get:
      summary: list all persons
      description: return all persons
      responses:
        '200':
          description: list of all persons
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    name:
                      type: string
                    location:
                      type: string
                    birthDate:
                      type: string
